### PR TITLE
Per project extensions

### PR DESCRIPTION
**Pull request by shaddockh**
I took what you started for the per-project extensions and did the following:
- Moved the process that searches and loads up the project extensions into it's own extension called `ProjectBasedExtensionLoader`.  

This extension listens for the project load event and then loads up any extensions it finds.  I needed to override the duktape method that resolves require statements to that it can successfully load in the extensions from the project folder and also resolve any imports those extensions may use.  

On OSX, trying to require in an absolute path (ie: require("/Users/..."); was throwing a duktape error (it didn't like the "/" at the beginning), but I'm not sure how it behaves on Windows.  So to get around that, I prefix the require calls with:  "project:" and then the custom require resolver handles it from there.  
- Added a new service registry for UI Services so that extensions can access UI elements that were exposed
- Injected the menu creation functions you put together into the UIService so that they can be called
- Any other UI resources should be injected the same way if you want access to them from an extension.  The extension can't reach back into the editor unless it's exposed as public object or method on the UIServiceRegistry
- Modified the interfaces for the extensions and the registries so that extensions only need to bring in the EditorWork.d.ts 

Here is the example project extension:

``` typescript
/// <reference path="../typings/Atomic/AtomicWork.d.ts" />
/// <reference path="../typings/Atomic/Editor.d.ts" />
/// <reference path="../typings/Atomic/EditorWork.d.ts" />

// import PanoramicBuilderWindow = require("./PanoramicBuilderWindow");

// the following import tests the ability of the project based extension to import other files in project
import {msg} from "./test";
const PanoramicBuilderServiceMenuItem = "Panoramic Builder";

class PanoramicBuilderService implements Editor.HostExtensions.HostEditorService, Editor.HostExtensions.ProjectService {


    name: string = "PanoramicBuilderService";
    description: string = "This service provides panoramic builder functionality.";

    private serviceLocator: Editor.HostExtensions.HostServiceLocator = null;

    initialize(serviceLoader: Editor.Extensions.ServiceLoader) {
        Atomic.print("PanoramicBuilderService.initialize");

        this.serviceLocator = <Editor.HostExtensions.HostServiceLocator>(serviceLoader);
        if (this.serviceLocator) {
            this.serviceLocator.projectServices.register(this);
            this.serviceLocator.uiServices.register(this);
        }
    }
    projectUnloaded() {
        this.serviceLocator.uiServices.removePluginMenuItemSource(PanoramicBuilderServiceMenuItem);

        Atomic.print("PanoramicBuilderService.projectUnloaded");
        if (this.serviceLocator) {
            this.serviceLocator.projectServices.unregister(this);
            this.serviceLocator.uiServices.unregister(this);
        }
    }
    projectLoaded(ev: Editor.EditorEvents.LoadProjectEvent) {
        Atomic.print("PanoramicBuilderService.projectLoaded " + msg);
        let menu = this.serviceLocator.uiServices.createPluginMenuItemSource(PanoramicBuilderServiceMenuItem, { "Edit Snap Settings" : ["edit snap settings"] });
    }
    playerStarted() {
        Atomic.print("PanoramicBuilderService.playerStarted");
    }

    menuItemClicked(refId: string): boolean {
        Atomic.print("PanoramicBuilderService.menuItemClicked: " + refId);
        // Here, hook in and respond to any menu ref ids that you care about.
        return true;
    }
}

const panoramicBuilderService = new PanoramicBuilderService();
export default panoramicBuilderService;

```
- test.ts

``` typescript

export const msg = "My Message";

```

Some things to think about and they may need to be extended in the future
- expose more UI functionality
- think about having a global location to pull extensions from, ie: ~/.atomicExtensions/*
- think about how to unload extensions

But I think this is a good start.  Let me know if you have any questions!!

### CODE REVIEW

**Comment by shaddockh** [comment]
One thing I noticed is that removing the menu item doesn't seem to work correctly.  This will cause the menu to duplicate if you close the project and reopen it.  I haven't had a chance to dig in and determine if it's a problem with the interop between the extension and the editor or a problem with removing menu items in Atomic.  
The host code to remove the menu item is getting called, it's just not removing the actual menu item.

**Comment by mattbenic** [comment]
Very cool :) 
I think the absolute path behavior you're seeing is expected. AFAIK when modules are resolved in TS, anything starting with /, ./, or ../ is considered relative: https://www.typescriptlang.org/docs/handbook/module-resolution.html

I'll check out the PR and land it if all checks out, and then look into the menu item removal.

**Comment by mattbenic** [comment]
Ok, landing. I had some trouble loading the plugin code initially, but it seems duktape falls over on the //# sourceMappingURL statement at the bottom of the compiled file. Compiling without the sourcemap it was fine. Have you run into that?

**Comment by shaddockh** [comment]
I'm not sure I've run tsc with inline source maps.  I either turn them off or have them built out as a separate file, but that's good information to know.

**Comment by mattbenic** [comment]
Ok. I'm working on getting a modal window displayed from the extension now, but the nice clean interface approach isn't going to work for something like that with subclasses. I get the distinct feeling we need to think about how some core classes (like ModalWindow) are defined, so they can be exported in a more externally usable way. This is something I'd like to discuss with you, you seem to have a much better grasp of TypeScript's different ways of including external code.

For the time being I'm going to add an ExtensionWindow class that will allow core methods to be passed to it, and a showModal method to the UIService that takes those methods and constructs an ExtensionWindow using them.

**Comment by shaddockh** [comment]
I need to think about it some, but I believe the approach your using above might be the way to do it for now.  This would allow you to instantiate a new blank canvas extension window and then just add the components you need to it by the extension.

The problem is that a Type reference needs to be exposed through the ServiceLocator _and_ be able to be descended from. (that's the tricky part and I'm not sure Typescript would allow that, but pure Javascript might).  The other option would be to have these classes defined in a shareable external location that can be used by both the editor and the extensions.

**Comment by mattbenic** [comment]
Yeah that's exactly the issue. It feels as if perhaps something like the Modal class belongs in the /Script/Typescript location.

I'm also moving the extensions into Resrouces/EditorData, since assets like turbobadger files and images need to be in a directory relative to one of the Resource paths to be accessible and it makes no sense having the script and resources split up. I'll have to see if filtering EditorData out from builds is possible. It's simple to do, just a question of whether the build expects anything from EditorData. I doubt it :)

**Comment by mattbenic** [comment]
Ok, I've got the plugin menu item removal fixed, and an extension service with a modal window working. I'd like to PR this to upstream master unless there's anything you'd like to add or change?

**Comment by shaddockh** [comment]
Go for it.  I'm sure if I run across anything I can just create a new PR.

**Pull request merged**
